### ISSUE TITLE
LẮP ĐÈNNN

### ISSUE THREAD

**Issue by BichNgocB16** [BichNgocB16/Lop-11A16-Nhom-05#5]

**Comment by veeveei** [comment]
ủa vô chưaaaaaaaa

**Comment by lngphthao** [comment]
hế lu

**Comment by BichNgocB16** [comment]
alo zô zô

**Comment by thaoyi46** [comment]
bé yi bị dính lời nguyền nựa rou

**Comment by thaoyi46** [comment]
hận đèn

**Comment by lngphthao** [comment]
lời nguyền gì zọ

**Comment by thaoyi46** [comment]
> lời nguyền gì zọ

cái bài lày nèee

**Comment by DuongThu11A1638** [comment]
hé lu mấy pàkkk

**Comment by lngphthao** [comment]
> > lời nguyền gì zọ
> 
> cái bài lày nèee

nói zậy không sợ thầy hẻ

**Comment by lngphthao** [comment]
> hé lu mấy pàkkk

hé lu béee

**Comment by thaoyi46** [comment]
> > > lời nguyền gì zọ
> > 
> > 
> > cái bài lày nèee
> 
> nói zậy không sợ thầy hẻ

gỡ =)))

**Comment by lngphthao** [comment]
> > > > lời nguyền gì zọ
> > > 
> > > 
> > > cái bài lày nèee
> > 
> > 
> > nói zậy không sợ thầy hẻ
> 
> gỡ =)))

tồi =))))

**Comment by DuongThu11A1638** [comment]
quà sanh nhựt đók

**Comment by PhamLinh2011** [comment]
Aloooo

**Comment by lngphthao** [comment]
> Aloooo

dẹee

**Comment by lngphthao** [comment]
bây giờ đề bài là đèn nhấp nháy đúng hem

**Comment by veeveei** [comment]
ủa lad cả đám làm 1 cái hả??

**Comment by DuongThu11A1638** [comment]
mình bàn cách làm hoii

**Comment by thaoyi46** [comment]
nô
mỗi bé tự làm mụt cái â

**Comment by DuongThu11A1638** [comment]
xoq lên tinker card lèmmm

**Comment by DuongThu11A1638** [comment]
đầu tin là phần khai báo nè

**Comment by veeveei** [comment]
> mình bàn cách làm hoii

okaiii pà

**Comment by lngphthao** [comment]
ụa tưởng phải gắn mạch trước rồi mới code chứ nhỉii

**Comment by thaoyi46** [comment]
gùi mấy cao nhân lên iii

**Comment by DuongThu11A1638** [comment]
tao nghĩ là mình chú thích trước viết theo ngôn ngữ nào trước ha

**Comment by BichNgocB16** [comment]
t nghĩ là t phải mò lại lại rec @@ kh bíc chi mô j hết

**Comment by PhamLinh2011** [comment]
> tao nghĩ là mình chú thích trước viết theo ngôn ngữ nào trước ha

Ngôn ngữ bậc kout =)))

**Comment by veeveei** [comment]
ủa mà yêu cầu là làm gì t quên rồi?? :)))

**Comment by thaoyi46** [comment]
nhóm này wấ đã =))

**Comment by DuongThu11A1638** [comment]
> ủa mà yêu cầu là làm gì t quên rồi?? :)))

đèn sáng 2s tắt 1s

**Comment by lngphthao** [comment]
![image](https://user-images.githubusercontent.com/91894451/141608088-5a5593ea-7adc-4f42-be4a-5b79cd1241bb.png)
bài mẫu nèeee

**Comment by DuongThu11A1638** [comment]
> > tao nghĩ là mình chú thích trước viết theo ngôn ngữ nào trước ha
> 
> Ngôn ngữ bậc kout =)))

C++

**Comment by lngphthao** [comment]
trong file bài 6 của thầy

**Comment by veeveei** [comment]
mà mình cũng

> > ủa mà yêu cầu là làm gì t quên rồi?? :)))
> 
> đèn sáng 2s tắt 1s

cảm uwnn lần nữa nheeeeee

**Comment by lngphthao** [comment]
mình lắp mạch trước rồi mới code chứ mọi người nhỉ @@

**Comment by lngphthao** [comment]
vậy mới xem code có chạy được hem

**Comment by PhamLinh2011** [comment]
> > > tao nghĩ là mình chú thích trước viết theo ngôn ngữ nào trước ha
> 
> > 
> 
> > Ngôn ngữ bậc kout =)))
> 
> 
> 
> C++

Đừng coá tát zu mặt tui 🥺

**Comment by DuongThu11A1638** [comment]
tui nói thêm sau ý bà hui mò :<

**Comment by BichNgocB16** [comment]
mạch nà cóa breadboard, arduino zới j nữa hongg

**Comment by DuongThu11A1638** [comment]
> mình lắp mạch trước rồi mới code chứ mọi người nhỉ @@

là giờ mình lên tinker lắp mạch hẻ

**Comment by lngphthao** [comment]
> > mình lắp mạch trước rồi mới code chứ mọi người nhỉ @@
> 
> là giờ mình lên tinker lắp mạch hẻ

đúng gòi

**Comment by lngphthao** [comment]
> mạch nà cóa breadboard, arduino zới j nữa hongg

điện trở với đèn nữa hay sao éee

**Comment by DuongThu11A1638** [comment]
> mạch nà cóa breadboard, arduino zới j nữa hongg



> > > mình lắp mạch trước rồi mới code chứ mọi người nhỉ @@
> > 
> > 
> > là giờ mình lên tinker lắp mạch hẻ
> 
> đúng gòi

mà làm sao dậy
mình tự tạo hẻ

**Comment by BichNgocB16** [comment]
> > mạch nà cóa breadboard, arduino zới j nữa hongg
> 
> > > > mình lắp mạch trước rồi mới code chứ mọi người nhỉ @@
> > > 
> > > 
> > > là giờ mình lên tinker lắp mạch hẻ
> > 
> > 
> > đúng gòi
> 
> mà làm sao dậy mình tự tạo hẻ

ùaaa

**Comment by DuongThu11A1638** [comment]
dô phần circut hẻ

**Comment by veeveei** [comment]
> dô phần circut hẻ

chắc v á m ưii

**Comment by BichNgocB16** [comment]
giờ zừa bàn zừa zo tinker lắp mạch nhe

**Comment by lngphthao** [comment]
dạaaa

**Comment by lngphthao** [comment]
![image](https://user-images.githubusercontent.com/91894451/141609361-321217dc-3b49-457e-8f78-d8ce3f856955.png)
mọi người lắp như này nhaaaa

**Comment by BichNgocB16** [comment]
okee pàaa

**Comment by PhamLinh2011** [comment]
Oke poà

**Comment by DuongThu11A1638** [comment]
zaaa

**Comment by thaoyi46** [comment]
yạaaaaa

**Comment by veeveei** [comment]
cái điện trở nằm đâu v má???

**Comment by BichNgocB16** [comment]
1 đầu ở lỗ dương

**Comment by BichNgocB16** [comment]
đầu còn lại lỗ nào cũng đc :)))

**Comment by thaoyi46** [comment]
thẳng hàng đèn led hãaa

**Comment by lngphthao** [comment]
đầu còn lại ở lỗ trên cái chỗ abcdef gì đóa

**Comment by DuongThu11A1638** [comment]
đrrrrr

**Comment by PhamLinh2011** [comment]
Làm sao để có thể làm trên điện thoại z

**Comment by lngphthao** [comment]
> thẳng hàng đèn led hãaa

thẳng hàng với cái chân cong cong của đèn led á

**Comment by thaoyi46** [comment]
uạ sao cái led cụa tui ngắn ngũn z

**Comment by PhamLinh2011** [comment]
> đầu còn lại ở lỗ trên cái chỗ abcdef gì đóa

Định tìm 5 chữ số khác nhau hẻ

**Comment by BichNgocB16** [comment]
> Làm sao để có thể làm trên điện thoại z

zo web đặt cái lap zề làm :>

**Comment by veeveei** [comment]
cái điện trở gán vô chân dương hả mấy bà??

**Comment by thaoyi46** [comment]
> Làm sao để có thể làm trên điện thoại z
qua phạm dăn chiêu nka

**Comment by BichNgocB16** [comment]
> cái điện trở gán vô chân dương hả mấy bà??

ùa 1 đầu chân dươngg

**Comment by DuongThu11A1638** [comment]
> uạ sao cái led cụa tui ngắn ngũn z

nối dây màu xám vô i bà

**Comment by PhamLinh2011** [comment]
> > Làm sao để có thể làm trên điện thoại z
> 
> 
> 
> zo web đặt cái lap zề làm :>

Cúc i 💔

**Comment by lngphthao** [comment]
> > đầu còn lại ở lỗ trên cái chỗ abcdef gì đóa
> 
> Định tìm 5 chữ số khác nhau hẻ

trời quơi đừng nhắc tón nữa :((((

**Comment by DuongThu11A1638** [comment]
tui xoq mạch rùi nè

**Comment by veeveei** [comment]
tui cũng vvvvv

**Comment by DuongThu11A1638** [comment]
![image](https://user-images.githubusercontent.com/91888451/141609482-844a5866-5608-4436-ab05-834ad65512e8.png)

**Comment by BichNgocB16** [comment]
của tui cũng y z áaa

**Comment by veeveei** [comment]
tui cũng y v mà chân đèn led ngắn hơn xíuuu

**Comment by thaoyi46** [comment]
![image](https://user-images.githubusercontent.com/91892294/141609492-c8bd1ac2-0748-4ee7-af9f-dcd72e7ef004.png)
yeah

**Comment by lngphthao** [comment]
> ![image](https://user-images.githubusercontent.com/91892294/141609492-c8bd1ac2-0748-4ee7-af9f-dcd72e7ef004.png) yeah

đầu tư quá zạ

**Comment by thaoyi46** [comment]
> > ![image](https://user-images.githubusercontent.com/91892294/141609492-c8bd1ac2-0748-4ee7-af9f-dcd72e7ef004.png) yeah
> 
> đầu tư quá zạ

đầu tư j âu

**Comment by BichNgocB16** [comment]
![image](https://user-images.githubusercontent.com/91891037/141609515-be3a6566-ed65-4f15-92a9-9e67e3b38d54.png)

**Comment by lngphthao** [comment]
![image](https://user-images.githubusercontent.com/91894451/141609522-6ab83163-5cb6-4804-9702-e9d0760ab712.png)

của tuôi nèee

**Comment by veeveei** [comment]
![image](https://user-images.githubusercontent.com/91890259/141609531-6b04b16c-9c38-4651-b994-6de187d7ce03.png)

**Comment by DuongThu11A1638** [comment]
@PhamLinh2011 bà thì saooooo

**Comment by PhamLinh2011** [comment]
> @PhamLinh2011 bà thì saooooo

Tui lonely

**Comment by thaoyi46** [comment]
> > @PhamLinh2011 bà thì saooooo
> 
> Tui lonely

qua phạm zăn chiêu ik

**Comment by lngphthao** [comment]
> > @PhamLinh2011 bà thì saooooo
> 
> Tui lonely

lonely sao bằng tui đượt :(

**Comment by PhamLinh2011** [comment]
Đợi tui 5' lấy xe ụn ụn ra net

**Comment by veeveei** [comment]
nhanhh lên pà ưuiiiii

**Comment by PhamLinh2011** [comment]
Tui xong r nee

**Comment by PhamLinh2011** [comment]
![image](https://user-images.githubusercontent.com/91890917/141610033-e75d011f-1838-4309-9cd0-0c9b727514da.jpeg)

**Comment by PhamLinh2011** [comment]
Xong ui neee

**Comment by thaoyi46** [comment]
dữ z taaa

**Comment by lngphthao** [comment]
ố kèeee

**Comment by lngphthao** [comment]
giờ qua code hẻ te

**Comment by thaoyi46** [comment]
gòi h sao nựaaa

**Comment by veeveei** [comment]
làm sao để làm mấy cái giây giây v mấy pà???

**Comment by DuongThu11A1638** [comment]
qua code iiii

**Comment by BichNgocB16** [comment]
![image](https://user-images.githubusercontent.com/91891037/141610084-bcb289a1-c8f1-4fe6-a019-fcd0ef13ad68.png)
code nè mnggg

**Comment by BichNgocB16** [comment]
đề là sáng 2s tắt 1s đúng hemmm

**Comment by veeveei** [comment]
ùa v h sửa gì bâyyy

**Comment by lngphthao** [comment]
hình như sửa cái dòng delay á

**Comment by lngphthao** [comment]
cái dòng 11

**Comment by DuongThu11A1638** [comment]
đổi 1 thành 2 hẻ

**Comment by DuongThu11A1638** [comment]
đún hơm

**Comment by PhamLinh2011** [comment]
> đổi 1 thành 2 hẻ

Hnhu z á nó mới sángg

**Comment by lngphthao** [comment]
> đổi 1 thành 2 hẻ

đúng gòi nèeee

**Comment by PhamLinh2011** [comment]
Đổi dòng 11 r coa đổi dòng 13 lun hongg

**Comment by DuongThu11A1638** [comment]
hok ngaaaaa

**Comment by thaoyi46** [comment]
1 nào dợoooo

**Comment by BichNgocB16** [comment]
![image](https://user-images.githubusercontent.com/91891037/141610204-9458a825-9d2c-40af-b332-f7b0c8e7eb8d.png)
z là đượt r hennn

**Comment by veeveei** [comment]
1000 đổi thành 2000 ở dòng 11 á m ưuiii

**Comment by BichNgocB16** [comment]
> 1 nào
chỗ delay dòng 11 á

**Comment by lngphthao** [comment]
> ![image](https://user-images.githubusercontent.com/91891037/141610204-9458a825-9d2c-40af-b332-f7b0c8e7eb8d.png) z là đượt r hennn

làm giống bngoc là đúng gòi nè

**Comment by DuongThu11A1638** [comment]
được rufiiii nefeeeeee mấy pé

**Comment by veeveei** [comment]
để t thử làm

**Comment by thaoyi46** [comment]
cíu béeeee

**Comment by DuongThu11A1638** [comment]
sao dọoo

**Comment by lngphthao** [comment]
mọi người ấn vô cái Start Simulation để xem đúng chưa nha

**Comment by veeveei** [comment]
![image](https://user-images.githubusercontent.com/91890259/141610253-f712cc3f-298f-4b7a-8a2c-11fde1114449.png)

**Comment by lngphthao** [comment]
tui làm được rồi hé hé

**Comment by BichNgocB16** [comment]
t đượt nèee

> mọi người ấn vô cái Start Simulation để xem đúng chưa nha

**Comment by thaoyi46** [comment]
> mọi người ấn vô cái Start Simulation để xem đúng chưa nha

à tui định hỏi này nàaaa

**Comment by DuongThu11A1638** [comment]
![image](https://user-images.githubusercontent.com/91888451/141610294-2320ee70-c6b1-4955-97c7-af8f06c2ad7b.png)

**Comment by thaoyi46** [comment]
đã wá đượt gùi nekkkk
![image](https://user-images.githubusercontent.com/91892294/141610316-f9e687c8-ba20-4b28-b937-54c3ef7cca91.png)

**Comment by lngphthao** [comment]
> đã wá đượt gùi nekkkk ![image](https://user-images.githubusercontent.com/91892294/141610316-f9e687c8-ba20-4b28-b937-54c3ef7cca91.png)

ố là la

**Comment by PhamLinh2011** [comment]
Z là xong ui đúng khom mng

**Comment by thaoyi46** [comment]
ik ngụuuuuu

**Comment by lngphthao** [comment]
dạ đúm gòiii

**Comment by lngphthao** [comment]
đi ngủ hoiiii

**Comment by DuongThu11A1638** [comment]
ngụ nào

**Comment by BichNgocB16** [comment]
ngụ ngonnnn

**Comment by PhamLinh2011** [comment]
Đi làm toán nào 🥰💔

**Comment by veeveei** [comment]
bái baii mngggg

**Comment by lngphthao** [comment]
> Đi làm toán nào 🥰💔

hum qua toy đã thức đến 3h sáng chỉ để làm tới được có bài 51 thui đóa :(

**Comment by lngphthao** [comment]
quá đao lòng

**Comment by BichNgocB16** [comment]
alo mng ưi, bữa mình làm chưa đúng đề á phải lắp 3 đèn giao thông lun :<
nên h mng zo làm típ nhaaaa

**Comment by DuongThu11A1638** [comment]
dậy giờ là sửa mạch lại đúng hok

**Comment by BichNgocB16** [comment]
ùa lắp thêm 2 đèn nữaaa

**Comment by veeveei** [comment]
mà code y chang hả mấy bà??

**Comment by lngphthao** [comment]
okela đợi chúng tui tíiiiii

**Comment by lngphthao** [comment]
> mà code y chang hả mấy bà??

hình như phải đổi á

**Comment by PhamLinh2011** [comment]
Z tui ra net lại hẻ ;))

**Comment by veeveei** [comment]
ủa mà có

> > mà code y chang hả mấy bà??
> 
> hình như phải đổi á

đổi như nào m ưiiiii

**Comment by thaoyi46** [comment]
là giờ gắn lại 2 đèn kia y chang cái lúc đầu é hã

**Comment by veeveei** [comment]
> Z tui ra net lại hẻ ;))
bà ráng đi bà ơiii

**Comment by thaoyi46** [comment]
ủa sao led sao nó màu đỏ hết dạaaa

**Comment by DuongThu11A1638** [comment]
bấm vô cái đèn á

**Comment by DuongThu11A1638** [comment]
xong có phần color eseeee

**Comment by BichNgocB16** [comment]
đúng ròi áaa

**Comment by thaoyi46** [comment]
gùi cái code tính saooo =(((

**Comment by lngphthao** [comment]
để tui đi tìm hiểu choaaa

> gùi cái code tính saooo =(((

**Comment by PhamLinh2011** [comment]
Mây bà, ghép xong r nma ghi code sao cho nó sáng lên giờ

**Comment by thaoyi46** [comment]
đợi @lngphthao cíuu

> Mây bà, ghép xong r nma ghi code sao cho nó sáng lên giờ

**Comment by DuongThu11A1638** [comment]
hay mình gửi hình cái mạch lên trước i coi đúng hok đã

**Comment by veeveei** [comment]
ê gắn điện trở ở đâu v??

**Comment by lngphthao** [comment]
![image](https://user-images.githubusercontent.com/91894451/141718062-168939d3-eaf7-4e55-bd50-cb339757857b.png)

chíuuu

**Comment by lngphthao** [comment]
> ê gắn điện trở ở đâu v??

gắn ở chân âm của đèn áaa

**Comment by DuongThu11A1638** [comment]
![image](https://user-images.githubusercontent.com/91888451/141718179-126f556c-7b08-49da-b53d-9f5c8113e97d.png)
cụa tui nèeee

**Comment by thaoyi46** [comment]
![image](https://user-images.githubusercontent.com/91892294/141718128-2fd2d974-f651-41e4-99d2-0fae23ef4efa.png)
mấy bà nghía dùm tui dới

**Comment by PhamLinh2011** [comment]
Tutu làm sao cho cái đèn nó bar mào khác nhau Z

**Comment by veeveei** [comment]
![image](https://user-images.githubusercontent.com/91890259/141718294-9d7e0798-a244-40e5-9bea-8c1825dfff59.png)

**Comment by lngphthao** [comment]
> Tutu làm sao cho cái đèn nó bar mào khác nhau Z

ấn vô cái đèn có cái chỗ colour é

**Comment by thaoyi46** [comment]
![image](https://user-images.githubusercontent.com/91892294/141718317-a2f52e5b-4ff6-4b5a-9e3b-7cf244f980d3.png)
tèn tenn

**Comment by lngphthao** [comment]
tui sắp mò được cái code gòiiiii

**Comment by PhamLinh2011** [comment]
> > Tutu làm sao cho cái đèn nó bar mào khác nhau Z
> 
> 
> 
> ấn vô cái đèn có cái chỗ colour é

Dza được gui

**Comment by BichNgocB16** [comment]
![image](https://user-images.githubusercontent.com/91891037/141718392-73bf955c-a436-43f7-90e5-f459315842af.png)
t cũng xong rouuu

**Comment by lngphthao** [comment]
tui mò được cái code rồi nè

**Comment by PhamLinh2011** [comment]
![image](https://user-images.githubusercontent.com/91890917/141718703-6203fed3-0326-462a-b661-bd2a8103170e.jpeg)

Đúng chưa mấy pàaa

**Comment by lngphthao** [comment]
ai chụp dòng code tao chỉ choaaaa

**Comment by thaoyi46** [comment]
![image](https://user-images.githubusercontent.com/91892294/141718940-35bcd2aa-ea67-4b0e-8c6f-9d829c530236.png)
này phãi hơmmmm

**Comment by PhamLinh2011** [comment]
> ![image](https://user-images.githubusercontent.com/91892294/141718940-35bcd2aa-ea67-4b0e-8c6f-9d829c530236.png)
> 
> này phãi hơmmmm
> 
> 
> 
> 

Nhìn hỉu gì chếch lìn ;((

**Comment by lngphthao** [comment]
oke đợi tui tí tui đánh giải thích trong một lần luôn cho dễ hiểu, gòi ai có chỗ nào thắc mắc thì hỏi tui trả lời cho

**Comment by BichNgocB16** [comment]
okiii

**Comment by PhamLinh2011** [comment]
Okuu

**Comment by lngphthao** [comment]
cái pinMode hiện tại á là đang điều khiển tất cả cái đèn luôn nè, nên bây giờ mình phải khai báo sao cho mỗi đèn tương ứng với chân Digital được cắm á

**Comment by veeveei** [comment]
là cắm mỗi đèm vô 1 chân hả m???

**Comment by lngphthao** [comment]
Cái pinMode hiện tại á là đang điều khiển tất cả cái đèn luôn nè, nên bây giờ mình phải khai báo sao cho mỗi đèn tương ứng với chân Digital được cắm á. Thì trong mạch tao đang cắm tương ứng là 3 chân 13,12,11 thì tao sẽ khai báo như trong hình. 

digitalWrite cũng giống vậy luôn, hiện tại là nó đang điều khiển tất cả các đèn và thời gian sáng vẫn là 1s nên mình sẽ chỉnh delay sau digitalWrite HIGH thành 2000 để đèn sáng 2s. Với hiện tại mình cần mỗi đèn sáng nối tiếp nhau nên mình sẽ code riêng cho mỗi đèn như bên dưới á, vậy là mỗi đèn sẽ sáng 2s tắt 1s rồi sẽ đến đèn kế tiếp.

Vậy là xong rùi đóaaaaaaaa, ai không hiểu hỏi tui nhaaa 


![image](https://user-images.githubusercontent.com/91894451/141719460-40b33d46-0078-46c1-9104-955c52cc173d.png)

**Comment by BichNgocB16** [comment]
đợi t load :(((((((((

**Comment by veeveei** [comment]
sao nhiều chữ v m :((((

**Comment by DuongThu11A1638** [comment]
say chữ 
xĩuuuuuu

**Comment by thaoyi46** [comment]
> Cái pinMode hiện tại á là đang điều khiển tất cả cái đèn luôn nè, nên bây giờ mình phải khai báo sao cho mỗi đèn tương ứng với chân Digital được cắm á. Thì trong mạch tao đang cắm tương ứng là 3 chân 13,12,11 thì tao sẽ khai báo như trong hình.
> 
> digitalWrite cũng giống vậy luôn, hiện tại là nó đang điều khiển tất cả các đèn và thời gian sáng vẫn là 1s nên mình sẽ chỉnh delay sau digitalWrite HIGH thành 2000 để đèn sáng 2s. Với hiện tại mình cần mỗi đèn sáng nối tiếp nhau nên mình sẽ code riêng cho mỗi đèn như bên dưới á, vậy là mỗi đèn sẽ sáng 2s tắt 1s rồi sẽ đến đèn kế tiếp.
> 
> Vậy là xong rùi đóaaaaaaaa, ai không hiểu hỏi tui nhaaa
> 
> ![image](https://user-images.githubusercontent.com/91894451/141719460-40b33d46-0078-46c1-9104-955c52cc173d.png)

cho bé vài phút tiêu hóa hết nhâ =)))

**Comment by PhamLinh2011** [comment]
> > Cái pinMode hiện tại á là đang điều khiển tất cả cái đèn luôn nè, nên bây giờ mình phải khai báo sao cho mỗi đèn tương ứng với chân Digital được cắm á. Thì trong mạch tao đang cắm tương ứng là 3 chân 13,12,11 thì tao sẽ khai báo như trong hình.
> 
> > 
> 
> > digitalWrite cũng giống vậy luôn, hiện tại là nó đang điều khiển tất cả các đèn và thời gian sáng vẫn là 1s nên mình sẽ chỉnh delay sau digitalWrite HIGH thành 2000 để đèn sáng 2s. Với hiện tại mình cần mỗi đèn sáng nối tiếp nhau nên mình sẽ code riêng cho mỗi đèn như bên dưới á, vậy là mỗi đèn sẽ sáng 2s tắt 1s rồi sẽ đến đèn kế tiếp.
> 
> > 
> 
> > Vậy là xong rùi đóaaaaaaaa, ai không hiểu hỏi tui nhaaa
> 
> > 
> 
> > ![image](https://user-images.githubusercontent.com/91894451/141719460-40b33d46-0078-46c1-9104-955c52cc173d.png)
> 
> 
> 
> cho bé vài phút tiêu hóa hết nhâ =)))

Em cũng z ;))

**Comment by veeveei** [comment]
là mấy cái code gần như y chang chỉ đổi lại mấy cái chân thôi hả m??

**Comment by lngphthao** [comment]
> là mấy cái code gần như y chang chỉ đổi lại mấy cái chân thôi hả m??

đúng gòiiii

**Comment by thaoyi46** [comment]
đúi =(((((

**Comment by BichNgocB16** [comment]
t thử đc r nèeeeeeeeeeee
![image](https://user-images.githubusercontent.com/91891037/141720615-f7262f10-4b88-4d66-bde5-ddeb0ac297ce.png)

**Comment by PhamLinh2011** [comment]
> t thử đc r nèeeeeeeeeeee
> 
> ![image](https://user-images.githubusercontent.com/91891037/141720615-f7262f10-4b88-4d66-bde5-ddeb0ac297ce.png)
> 
> 

Ê tao bic tao sai ở đou ui kẻm ơn Ngọc nghen

**Comment by DuongThu11A1638** [comment]
![image](https://user-images.githubusercontent.com/91888451/141720728-39e36593-3044-4872-bb85-93a61ac3a21b.png)
tui cũng được ùiiiiii

**Comment by lngphthao** [comment]
mọi người hiểu hết chưa, ai không hiểu thì hỏi nhee

**Comment by thaoyi46** [comment]
![image](https://user-images.githubusercontent.com/91892294/141720770-d664ada5-db7c-477d-8d51-8256bfa46ef2.png)
cho ló chạy thử mà thấy được thì okk rùi đk :>>>

**Comment by veeveei** [comment]
![image](https://user-images.githubusercontent.com/91890259/141720771-ff8d9aa9-9d8c-4ca2-8bea-6db0f55f3dd8.png)
 ủa làm v đúng chưa mấy bà?? tui thấy nó sáng sáng là chắc được rồi hennn

**Comment by PhamLinh2011** [comment]
Tui xong goy nghe

**Comment by DuongThu11A1638** [comment]
dậy là xoq ùi đún hokkk

**Comment by BichNgocB16** [comment]
ùi đúng honggg

**Comment by lngphthao** [comment]
à mọi người muốn đèn sáng hơn thì đổi điện trở từ 100 đến 220 ôm nhaaaaaaaa

**Comment by veeveei** [comment]
t muốn nó sáng banh nóc t làm 1000k ôm nó có nổ k bây ưi???

**Comment by lngphthao** [comment]
> t muốn nó sáng banh nóc t làm 1000k ôm nó có nổ k bây ưi???

cái gì vậy bàaaaa, nổ banh chành luôn bây giờ

**Comment by thaoyi46** [comment]
bye mụi ngừi em đi mum mum nhâaaa

**Comment by BichNgocB16** [comment]
t đổi thành 220 ôm cái đèn sáng lên lun nè ^^

**Comment by thaoyi46** [comment]
cyn cảm ơn @lngphthao nhiềuuuu

**Comment by lngphthao** [comment]
vậy là xong rùi đóa, đi ngủ thoyyyyyyyyyy

**Comment by PhamLinh2011** [comment]
Pupu mọi người nhooo

**Comment by veeveei** [comment]
chúc mnggg ngủ ngonnnnnnnnn

**Comment by BichNgocB16** [comment]
ngụ nhoaaaa, cãm ơn @lngphthao, bai mụi ngừiiiiiiiiiii

**Comment by veeveei** [comment]
bái baiii nheeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

**Comment by DuongThu11A1638** [comment]
> vậy là xong rùi đóa, đi ngủ thoyyyyyyyyyy

bà ngụ ngon hong mơ thấy ms team giống tớ :>>>

**Comment by lngphthao** [comment]
quá đã sai mạch lần 2 😔

**Comment by BichNgocB16** [comment]
khó :<

**Comment by thaoyi46** [comment]
alo các tềnh iu oiiii, cái mạch hum qua của mình hơi sai á ngaa

**Comment by veeveei** [comment]
v sửa ở đâu v m ưi :((((

**Comment by DuongThu11A1638** [comment]
yi46 biết sửa sao hongggg

**Comment by thaoyi46** [comment]
![image](https://user-images.githubusercontent.com/91892294/141892567-0cdfd8ee-2101-46f2-a58d-1bb76601b3a9.png)
mình phải để dòng điện chạy qua điện trở trước rồi mới vào đèn LED.
nên phải lắp lại giống cụa t nèee

**Comment by veeveei** [comment]
tất cả đều gắm vô chân dương hết hả m??

**Comment by BichNgocB16** [comment]
tất cả là chân nào á

**Comment by PhamLinh2011** [comment]
Z còn cái code coa sửa gì hong z hay để yên vẫn đúng ée

**Comment by thaoyi46** [comment]
nà sao z mấy bé@@
kui chỉ biết là mình chuyển cái đtrở qua hoy marr

**Comment by thaoyi46** [comment]
> Z còn cái code coa sửa gì hong z hay để yên vẫn đúng ée

t để yên akk

**Comment by BichNgocB16** [comment]
![image](https://user-images.githubusercontent.com/91891037/141895301-1f32821c-6f34-460c-a0d3-0fe663e002db.png)
hum qua mình gắn z nè, là cái chân đèn với dây gnd nối chân âm á

**Comment by PhamLinh2011** [comment]
> > Z còn cái code coa sửa gì hong z hay để yên vẫn đúng ée
> 
> 
> 
> t để yên akk

Keee

**Comment by BichNgocB16** [comment]
còn @thaoyi46 mới gửi là nối chân dương

**Comment by lngphthao** [comment]
![image](https://user-images.githubusercontent.com/91894451/141896965-e652fa8d-63a3-4957-befd-28c106ea9ab6.png)

tui nối như này đúng trưa mọi ngườiii

**Comment by veeveei** [comment]
![image](https://user-images.githubusercontent.com/91890259/141897237-b46ca267-bee3-4568-94d9-4f1a0aba42eb.png)
 chắc đúng gòi hennn

**Comment by DuongThu11A1638** [comment]
![image](https://user-images.githubusercontent.com/91888451/141898286-a1ba0d8c-28a3-4bd8-8e1c-80b018ef3585.png)
cụa tui nè

**Comment by BichNgocB16** [comment]
![image](https://user-images.githubusercontent.com/91891037/141898677-6c6f8cc5-0e95-4f2f-a730-359c23fb86d2.png)
t cũng giống mng áaa

**Comment by PhamLinh2011** [comment]
Đợi tui tí nghennn

**Comment by PhamLinh2011** [comment]
Tui đang mượn được lap uii

**Comment by PhamLinh2011** [comment]
![image](https://user-images.githubusercontent.com/91890917/141904114-310b8be0-09f3-4d88-a807-68a7d4420e17.jpeg)

Xong rui ngaaaaa

**Comment by thaoyi46** [comment]
wâ xịn nhâ

**Comment by veeveei** [comment]
v là xong rồi hẻ mng???

**Comment by DuongThu11A1638** [comment]
xong ùi phải hong mấy béee

**Comment by thaoyi46** [comment]
z tạm bịt cả nhà iu của kem nkaaa
i khò khò
wa' mệch mõi =(((

**Comment by PhamLinh2011** [comment]
Pupu mng nhoéeee

**Comment by BichNgocB16** [comment]
bai baiii

**Comment by DuongThu11A1638** [comment]
ngụ ngonnnn

**Comment by veeveei** [comment]
mnggg ngủ ngonnnnn nheeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
